import React, { useState, useEffect } from "react";

import { Loader, Card, FormField } from "../components";

const Home = () => {
  const [loading, setLoading]: Array<any> = useState(false);
  const [allPosts, setAllPosts]: Array<any> = useState(null);

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#22238] text-[32px]">The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">Browse through a collection of imaginative and visually stunnings images generated by DALL-E AI</p>
      </div>

      <div className="mt-10">
        <FormField />
      </div>

      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ) : (
          <></>
        )}
      </div>
    </section>
  );
};

export default Home;
